### ISSUE TITLE
nullpointer exception while using AdaptiveGridFTPClient

### ISSUE THREAD

**Issue by NISH1001** [arif-zaman/throughput-optimization#8]
Hi,

I am currently trying to evaluate Faclon's ability on large-scale data transfer. While trying to use [AdaptiveGridFTPClient](https://github.com/arif-zaman/Falcon-File-Transfer-Optimizer/tree/master/Falcon-GridFTP/AdaptiveGridFTPClient) as mentioned in the readme, I am unable to execute the runner. My configuration file is basically pointing to the local-hosted ftp server (as a test). My hostname keeps on coming as null while executing.

Can you please help me with this?
- First, can you provide an example configuration on how I can use ftp there?
- Secondly, hostname keeps on coming as `null` no matter what.
- What do `INPUT_DIR` and `OUTPUT_DIR` represent in `src/main/java/client/ConfigurationParams.java`? Do I need to update the paths?
- How do we do authenticated ftp with username and password in this?

I have attached a screenshot 
![image](https://user-images.githubusercontent.com/4786694/154356147-b111c2aa-aad5-4a8d-bed4-530a8eb287f5.png)

(My background: I am a researcher at UAH)

**Comment by arif-zaman** [comment]
Hi!
This application is developed for GridFTP protocol (as most HPC centers support GridFTP), which follows a grid authentication mechanism. We extended Globus-toolkit, which takes care of the authentication part. You can create a local GridFTP server without authentication enabled for testing. Unfortunately, the Globus toolkit is retired, but there are open source community projects you can follow like this one - https://gridcf.org/gct-docs/

**Comment by NISH1001** [comment]
@arif-zaman Thank you for the response. I have some followup queries:

- While running `AdaptiveGridFTP`, do we need to run `receiver.py` and `sender.py` too?
- In standard mode when running `receiver.py` and `sender.py` I am getting the following error:
- 
![image](https://user-images.githubusercontent.com/4786694/156448334-4f1516c1-7a64-4818-bc80-64d8a0d0dbbc.png)


It'd be pretty helpful if we could get a general flow of execution of the code. Like which servers to run when. Or a real example of configurations would help. Thanks.

Can you please help clarifying this?

**Comment by arif-zaman** [comment]
Q: While running AdaptiveGridFTP, do we need to run receiver.py and sender.py too?
A: No, but you need to run the local optimization server (example: src/main/python/socket_gradient.py) before running the transfer. Also, you need to run the GridFTP server on both sender and receiver hosts.

For Standard mode: Please start receever.py first at the destination host, then sender.py at the source host. In the screenshot, the worker process is getting an error. blocksize value type is probably float rather than a positive integer. (line 155 in sender.py according to the latest version of the codebase)
